import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import "../globals.css";
import { Users, Building } from 'lucide-react';

// Using Inter instead of Geist
const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Using Roboto Mono instead of Geist Mono
const robotoMono = Roboto_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${robotoMono.variable}`}>
      <body>
        <div className="flex min-h-screen flex-col">
          <main className="flex-1">
            <div className="flex items-center justify-between p-4 bg-gray-100 border-b border-gray-300">
              <div className="flex items-center space-x-2">
                <Users className="h-6 w-6 text-blue-600" />
                <span className="text-xl font-semibold">Admin</span>
              </div>
              <div className="flex items-center space-x-2">
                <Building className="h-6 w-6 text-blue-600" />
                <span className="text-xl font-semibold">Company</span>
              </div>
            </div>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}