import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import "../globals.css";
import { Users, Building } from 'lucide-react';

// Using Inter instead of Geist
const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Using Roboto Mono instead of Geist Mono
const robotoMono = Roboto_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${robotoMono.variable}`}>
      <body>
       
          
            
            {children}
         
      </body>
    </html>
  );
}