import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import {  Users, Building } from 'lucide-react';
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-blue-600 text-white p-4 shadow-y border-y border-gray-200">
            <div className="max-w-4xl mx-auto flex justify-between items-center">
                <h1 className="text-2xl font-bold">KWF_SAAS</h1>
                <div className="text-sm">
                    <span>Your go-to solution for business management</span>
                </div>
            </div>
        </nav>
        <div className="min-h-screen flex bg-gray-50">
        <div className="hidden lg:flex lg:w-1/2 bg-gradient-to-r from-blue-600 to-indigo-600 text-white p-12 flex-col justify-between">
                <div>
                    <h1 className="text-5xl font-extrabold mb-4 animate-fade-in">KWF-SAAS</h1>
                    <p className="text-blue-100 text-lg">Your Ultimate Contact Management Solution</p>
                </div>
                
                <div className="space-y-8">
                    <div className="flex items-start space-x-4 animate-slide-in">
                        <div className="p-3 bg-blue-500 rounded-lg">
                            <Users className="w-6 h-6" />
                        </div>
                        <div>
                            <h3 className="font-semibold mb-1">Customizable Contact Fields</h3>
                            <p className="text-blue-100 text-sm">Tailor your contact management to your organizations specific needs</p>
                        </div>
                    </div>
                    
                    <div className="flex items-start space-x-4 animate-slide-in">
                        <div className="p-3 bg-blue-500 rounded-lg">
                            <Building className="w-6 h-6" />
                        </div>
                        <div>
                            <h3 className="font-semibold mb-1">Multi-Organization Support</h3>
                            <p className="text-blue-100 text-sm">Perfect for businesses of all types and sizes</p>
                        </div>
                    </div>
                </div>

                <div className="text-sm text-blue-100">
                    Trusted by hundreds of organizations worldwide
                </div>
            </div>
        {children}
        </div>
      </body>
    </html>
    );
};

